plugins {
	id("scala")
	id 'fabric-loom' version '1.10-SNAPSHOT'
}

group = project.maven_group
archivesBaseName = project.archives_base_name
version = project.mod_version + "+mc" + project.minecraft_version

repositories {
	maven { url 'https://maven.fabricmc.net/' }
	mavenCentral()
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
  modImplementation "net.fabricmc:fabric-language-scala:0.3.1.+"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

scala {
	scalaVersion = "3.7.0"
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = "UTF-8"
	options.release.set(17)
}

tasks.withType(ScalaCompile).configureEach {
    options.encoding = "UTF-8"
}

processResources {
    // These are correct for declaring inputs to the task for caching
    inputs.property "version", project.version
    inputs.property "loader_version", project.loader_version
    inputs.property "minecraft_version", project.minecraft_version

    def projectVersion = project.version
    def loaderVersion = project.loader_version
    def minecraftVersion = project.minecraft_version

    filesMatching("fabric.mod.json") {
				// Replace the version in the fabric.mod.json file
        expand "version": projectVersion,
               "loader_version": loaderVersion,
               "minecraft_version": minecraftVersion
    }
}
